management:
  endpoints:
    web:
      exposure:
        include: health

app:
  kafka:
    topic: sports-events
    dlt: sports-events-dlt # use it later
    bootstrap-servers: localhost:9092
    producer:
      acks: "all" # want to receive ACK after every message -> no data loss
      retries: 3
      retry-backoff-ms: 300
      group-id: sports-events-consumer-group

external-api:
  url: http://localhost:8080//api/v1/mock/events
#  you can use this public url for testing different timeouts -> Postman tends to fail every x reqs
#  url: https://3aed67d8-f1a8-4962-992c-5a778d4d39c3.mock.pstmn.io/events
